@startuml
title I Can Haz Cheezborger Business Context

:User: as user

[I Can Haz Cheezborger] as core #eeee99

cloud {
[YouTube] as youtube
[TikTok] as tiktok
[external images] as internet
[Azure services] as azureService
[Azure hosting] as azureHost
database "Azure storage" as azureData
[Disqus] as disqus
}

user -.-> core : uses

core -.-> youtube : reads
core -.-> tiktok : reads
core -.-> internet : reads

core <-.-> azureService : read/write content
core <-.-> azureHost : read/write content
core <-.-> azureData : read/write content
core <-.-> disqus : read/write content

@enduml
