@startuml
title Level 1 Subsystems

component "I Can Haz Cheezborger" as core #eeee99 {

    [Site Creator]
    [User Registry]
    [Content Editor]
    [Content Moderation Editor]
    [Permissions Editor]
    [SEO Editor]
    [Mashup Creator]
    [External Content Acquirer]
    [Forums] as forums
    [Data Harvester]
    [Trend Analyzer]
}

component Disqus

forums --> Disqus

@enduml
