@startuml
title Level 1 Subsystems

component "I Can Haz Cheezborger" as core #eeee99 {

'    package "Site" as sitePkg {
        [Site Creator] as creator
        [Content Editor] as contentEdit
        [Content Moderation Editor] as moderator
        [Data Harvester] as harvester
'    }
    
    [User Registry] as users
    
    [Permissions Editor] as permission
    
    [Mashup Creator] as mashup
    
    [External Asset Acquirer] as acquire
    
    [Trend Analyzer] as analyzer
}

component Disqus
component "Azure Hosted Site" as site
cloud "Azure Storage" as storage {
    database "Page usage" as pageUsage
    database "Users" as userData
    database "Assets" as assetData
    database "Moderation" as moderationData
}

acquire ..> assetData : writes

analyzer ..> harvester : uses
analyzer ..> permission : uses

creator ..> site : edits

contentEdit ..> site : edits
contentEdit ..> assetData : reads

harvester ..> site : reads
harvester ..> pageUsage : writes

mashup ..> assetData : read/write

moderator ..> site : edits
moderator ..> permission : uses
moderator ..> moderationData : edits

permission ..> userData : edits

site ..> Disqus : use
site ..> assetData : read
site ..> permission : uses

users ..> userData : read/write
users ..> permission : uses

@enduml
